# Generated by Django 3.1.7 on 2021-03-01 16:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('contact', models.CharField(default='', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerTutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollmentDate', models.DateTimeField(verbose_name=datetime.datetime(2021, 3, 1, 16, 5, 20, 163553, tzinfo=utc))),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BookTutor.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('code', models.CharField(default='', max_length=30)),
                ('address', models.CharField(default='', max_length=100)),
                ('duration', models.IntegerField(default=0)),
                ('level', models.CharField(default='', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reg_no', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('contact', models.CharField(default='', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TutorSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('subjectId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BookTutor.subject')),
                ('tutorId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BookTutor.tutor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TutorRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(default=10)),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BookTutor.customer')),
                ('tutorId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BookTutor.tutor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.TextField(default='')),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BookTutor.customer')),
                ('tutorId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BookTutor.tutor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField(default=0)),
                ('tutorCustomerId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BookTutor.customertutor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customertutor',
            name='tutorSubject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BookTutor.tutorsubject'),
        ),
    ]
