# Generated by Django 3.1.7 on 2021-03-10 14:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BookTutor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('startDate', models.DateTimeField(default=datetime.datetime(2021, 3, 10, 14, 58, 34, 241839, tzinfo=utc))),
                ('endDate', models.DateTimeField(default=datetime.datetime(2021, 3, 12, 14, 58, 34, 241839, tzinfo=utc))),
                ('price', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('subjectId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BookTutor.subject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='address',
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='street',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tutor',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tutor',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=10),
        ),
        migrations.AddField(
            model_name='tutor',
            name='street',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='customertutor',
            name='enrollmentDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 14, 58, 34, 241839, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='SessionCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BookTutor.customer')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BookTutor.session')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='session',
            name='tutorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BookTutor.tutor'),
        ),
        migrations.CreateModel(
            name='InvoiceSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BookTutor.customer')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BookTutor.session')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
