# Generated by Django 3.1.7 on 2021-04-09 09:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BookTutor', '0005_auto_20210407_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Others', max_length=10),
        ),
        migrations.AlterField(
            model_name='customertutor',
            name='enrollmentDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 9, 30, 36, 319391, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='session',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 11, 9, 30, 36, 320401, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='session',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 9, 30, 36, 320401, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Others', max_length=10),
        ),
        migrations.CreateModel(
            name='TutorSubjectSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time', models.DateTimeField(default=datetime.datetime(2021, 4, 9, 9, 30, 36, 318391, tzinfo=utc))),
                ('tutorSubject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BookTutor.tutorsubject')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
