# Generated by Django 3.1.7 on 2021-04-11 05:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BookTutor', '0006_auto_20210409_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorsubjectschedule',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 11, 5, 16, 3, 427443, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customertutor',
            name='enrollmentDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 11, 5, 16, 3, 427443, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='session',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 13, 5, 16, 3, 428443, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='session',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 11, 5, 16, 3, 428443, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tutorsubjectschedule',
            name='time',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
    ]
