# Generated by Django 3.1.7 on 2021-04-14 11:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BookTutor', '0007_auto_20210411_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertutor',
            name='enrollmentDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 14, 11, 11, 38, 662064, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='session',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 16, 11, 11, 38, 663063, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='session',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 14, 11, 11, 38, 663063, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tutorrating',
            name='rating',
            field=models.FloatField(default=10.0),
        ),
        migrations.AlterField(
            model_name='tutorsubjectschedule',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 14, 11, 11, 38, 661064, tzinfo=utc)),
        ),
    ]
