# Generated by Django 3.1.7 on 2021-04-14 15:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BookTutor', '0008_auto_20210414_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertutor',
            name='enrollmentDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 14, 15, 38, 31, 607029, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='session',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 16, 15, 38, 31, 607029, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='session',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 14, 15, 38, 31, 607029, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tutorsubjectschedule',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 14, 15, 38, 31, 605935, tzinfo=utc)),
        ),
    ]
